# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_PUBLIC']
  config.secret_key = ENV['MAILJET_PRIVATE']
  config.default_from = 'dautheville@hotmail.com'

end
